version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
      - MYSQL_DB=elections
    ports:
      - 3306:3306

volumes:
  mysql:
    driver: local